title: Kashmira # your name (or website title) here
logo: "/images/IMG_0077.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  GES Major & Biological science Minor, 
  currently aiming for GIS Certificate
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
